name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Pull
        run: |
          echo Hostname:
          hostname
          cd "C:\\Users\\Administrator\\Documents\\Web Site"
          git pull
        shell: cmd