name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get dir
        run: cd "..\..\..\.."
      - name: Change dir
        run: |
          dir
      - name: Pull
        run: git pull