name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: CD
      run: cd "C:\\Users\\Administrator\\Documents\\Web Site"
      - name: Pull
      run: git pull